# Generated by Django 4.2.4 on 2023-08-04 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoV1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('todoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todoV1.todoitem')),
            ],
        ),
    ]
